# Generated by Django 3.1.4 on 2020-12-30 15:11

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190225_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(default='defo', upload_to=app1.models.update_filename),
        ),
    ]
